global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'load-balancer'
    static_configs:
      - targets: ['load-balancer:5000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node_exporter:9100' ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'locust'
    scrape_interval: 5s
    static_configs:
        - targets:
          - locust-metrics-exporter:9646

remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus"
    remote_timeout: 30s
    write_relabel_configs:
      - source_labels: [__name__]
        target_label: metric_name