apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
        - name: backend1
          image: us-central1-docker.pkg.dev/adaptive-load-balancer-2/backend-services/backend1:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend1-service
spec:
  type: LoadBalancer
  selector:
    app: backend1
  ports:
    - port: 80
      targetPort: 5000