apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
        - name: backend2
          image: us-central1-docker.pkg.dev/adaptive-load-balancer-1/backend-services/backend2:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend2-service
spec:
  type: LoadBalancer
  selector:
    app: backend2
  ports:
    - port: 80
      targetPort: 5000