apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend5
  template:
    metadata:
      labels:
        app: backend5
    spec:
      containers:
        - name: backend5
          image: us-central1-docker.pkg.dev/adaptive-load-balancer-1/backend-services/backend5:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend5-service
spec:
  type: LoadBalancer
  selector:
    app: backend5
  ports:
    - port: 80
      targetPort: 5000