apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend3
  template:
    metadata:
      labels:
        app: backend3
    spec:
      containers:
        - name: backend3
          image: us-central1-docker.pkg.dev/adaptive-load-balancer-1/backend-services/backend3:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend3-service
spec:
  type: LoadBalancer
  selector:
    app: backend3
  ports:
    - port: 80
      targetPort: 5000