apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend6
  template:
    metadata:
      labels:
        app: backend6
    spec:
      containers:
        - name: backend6
          image: us-central1-docker.pkg.dev/adaptive-load-balancer-2/backend-services/backend6:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend6-service
spec:
  type: LoadBalancer
  selector:
    app: backend6
  ports:
    - port: 80
      targetPort: 5000