apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-balancer
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      containers:
        - name: load-balancer
          image: us-central1-docker.pkg.dev/adaptive-load-balancer-1/backend-services/load-balancer:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  type: LoadBalancer
  selector:
    app: load-balancer
  ports:
    - port: 80
      targetPort: 5000